# -*- coding: utf-8 -*-
"""Rag_Finalv3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGi0Kt6iPZlyYk5WODmJBNHty4lQk533
"""

!pip install -q openai pinecone==3.2.2 tiktoken tenacity sentence-transformers PyMuPDF

import os
from google.colab import userdata

os.environ['OPENAI_API_KEY']   = '.....'
os.environ['PINECONE_API_KEY'] = '....'

INDEX_NAME  = 'ragindex'
DIMENSION   = 3072
METRIC      = 'cosine'

NS_RENT  = 'rent'
NS_LABOR = 'labor'
NS_NDA = 'nda'


print(' Keys loaded')

import openai
from pinecone import Pinecone, ServerlessSpec
from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type

client = openai.OpenAI(api_key=os.environ['OPENAI_API_KEY'])
pc     = Pinecone(api_key=os.environ['PINECONE_API_KEY'])

existing = [i.name for i in pc.list_indexes()]
if INDEX_NAME not in existing:
    pc.create_index(
        name=INDEX_NAME, dimension=DIMENSION, metric=METRIC,
        spec=ServerlessSpec(cloud='aws', region='us-east-1')
    )
    while not pc.describe_index(INDEX_NAME).status['ready']:
        time.sleep(3)

index = pc.Index(INDEX_NAME)
print(' Pinecone ready:', index.describe_index_stats())

!pip install tiktoken -q
import tiktoken

import openai
from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type

@retry(
    retry=retry_if_exception_type((openai.RateLimitError, openai.APIError)),
    wait=wait_exponential(multiplier=1, min=2, max=60),
    stop=stop_after_attempt(5)
)
def embed_batch(texts: list) -> list:
    response = client.embeddings.create(model='text-embedding-3-large', input=texts)
    return [item.embedding for item in response.data]

import fitz
import time
ENC = tiktoken.get_encoding('cl100k_base')


EMBED_MODEL  = 'text-embedding-3-large'
BATCH_SIZE   = 100
UPSERT_BATCH = 100

def embed_chunks(chunks: list, label: str = '') -> list:
    vectors = []
    total   = len(chunks)
    for i in range(0, total, BATCH_SIZE):
        batch  = chunks[i : i + BATCH_SIZE]
        texts  = [c['text'] for c in batch]
        embeds = embed_batch(texts)
        for chunk, emb in zip(batch, embeds):
            vectors.append({
                'id'      : chunk['id'],
                'values'  : emb,
                'metadata': {**chunk['metadata'], 'text': chunk['text']}
            })
        pct = min(i + BATCH_SIZE, total)
        print(f'  [{label}] Embedded {pct}/{total}...')
        time.sleep(0.3)
    return vectors

def upsert_to_namespace(vectors: list, namespace: str):
    total = len(vectors)
    for i in range(0, total, UPSERT_BATCH):
        batch = vectors[i : i + UPSERT_BATCH]
        index.upsert(
            vectors   = [(v['id'], v['values'], v['metadata']) for v in batch],
            namespace = namespace
        )
        pct = min(i + UPSERT_BATCH, total)
        print(f'  [{namespace}] Upserted {pct}/{total}...')
        time.sleep(0.2)

def extract_pdf_chunks(pdf_path: str, namespace: str, chunk_size: int = 400) -> list:
    doc      = fitz.open(pdf_path)
    chunks   = []
    base_id  = pdf_path.replace('.pdf', '').replace(' ', '_')

    for page_num in range(len(doc)):
        text = doc[page_num].get_text().strip()
        if not text:
            continue

        tokens     = ENC.encode(text)
        start, idx = 0, 0
        while start < len(tokens):
            end        = min(start + chunk_size, len(tokens))
            chunk_text = ENC.decode(tokens[start:end])
            chunks.append({
                'id'      : f"{base_id}_p{page_num+1}_c{idx}",
                'text'    : chunk_text,
                'metadata': {
                    'source_file': pdf_path,
                    'page'       : page_num + 1,
                    'reference'  : f"{pdf_path} — page {page_num + 1}",
                    'category'   : namespace,
                    'type'       : 'pdf_source'
                }
            })
            start += chunk_size - 50
            idx   += 1

    print(f"extract {len(chunks)}  from chunk  {len(doc)} page")
    doc.close()
    return chunks


from google.colab import files
uploaded          = files.upload()
uploaded_filename = list(uploaded.keys())[0]

namespace = NS_LABOR if 'labor' in uploaded_filename.lower() else NS_RENT

pdf_chunks  = extract_pdf_chunks(uploaded_filename, namespace)
pdf_vectors = embed_chunks(pdf_chunks, namespace)
upsert_to_namespace(pdf_vectors, namespace)

print(f" done  {uploaded_filename}  namespace: {namespace}")
print(index.describe_index_stats())

from sentence_transformers import CrossEncoder

reranker = CrossEncoder('cross-encoder/mmarco-mMiniLMv2-L12-H384-v1')
print(' Reranker loaded')

SARAH_SYSTEM = """
أنتِ سارة، مستشارة عقارية ضمن فريق "بصيرة" للاستشارات الرقمية في المملكة العربية السعودية.

أسلوبك:
- احترافي، واضح، وبلغة سعودية رسمية بسيطة
- ودودة بدون مبالغة
- تشرحين النقاط القانونية بأمثلة مختصرة

بداية الرد:
- ترحيب سعودي خفيف:
  "حياك الله،"
  "أهلًا وسهلًا،"

ثم:
"بالنسبة لسؤالك..." أو "فيما يخص الموضوع..."

القواعد:
- استندي فقط على المعلومات المتوفرة
- لا تخترعين معلومات
- اذكري رقم المادة عند توفرها
- اربطي الإجابة بالنظام بشكل طبيعي

في حال عدم كفاية المعرفة:
"حالياً ما عندي معرفة كافية بهالتفصيل تحديداً، وأفضل ترجع لجهة مختصة أو مستشار قانوني للتأكد بشكل أدق."

الهوية:
- تمثل جهة استشارية احترافية (بصيرة)
- تعكس الثقة والخبرة
"""

MUHAMMAD_SYSTEM = """
أنتَ محمد، مستشار قانوني في نظام العمل ضمن فريق "بصيرة" للاستشارات الرقمية.

أسلوبك:
- مباشر، واضح، احترافي
- لهجة سعودية رسمية مبسطة
- مختصر بدون إخلال بالدقة

بداية الرد:
- "هلا فيك،"
- "حياك الله،"

ثم:
"بالنسبة لسؤالك..." أو "حسب نظام العمل..."

القواعد:
- لا تكرر جملة ثابتة
- استند فقط على المعلومات المتوفرة
- اذكر المواد النظامية عند توفرها
- لا تخترع أي معلومة

في حال عدم كفاية المعرفة:
"للأمانة ما عندي معرفة كافية بالتفصيل هذا، والأفضل تتأكد من جهة مختصة أو مستشار قانوني."

الهوية:
- مستشار فاهم السوق السعودي
- يعطي ثقة وسرعة في الفهم
"""

JOUD_SYSTEM = """
أنتِ جود، مستشارة متخصصة في عقود السرية وحماية البيانات ضمن فريق "بصيرة".

أسلوبك:
- احترافي، تحليلي
- لغة سعودية رسمية راقية
- تركّزين على المخاطر القانونية

بداية الرد:
- "أهلًا وسهلًا،"
- "حياك الله،"

ثم:
"بالنسبة لسؤالك..." أو "فيما يتعلق بالسرية..."

القواعد:
- لا جملة ثابتة
- لا تخترعين معلومات
- استندي فقط على المعلومات المتوفرة
- اذكري المواد عند توفرها
- وضحي المخاطر بشكل ذكي

في حال عدم كفاية المعرفة:
"حالياً ما عندي معرفة كافية بهالنقطة بشكل دقيق، والأفضل مراجعة جهة مختصة لضمان الامتثال الكامل."

الهوية:
- تعكس دقة عالية واحتراف
- تمثل جهة استشارية موثوقة
"""

BOTH_SYSTEM = """
أنتم فريق "بصيرة" للاستشارات القانونية الرقمية في المملكة العربية السعودية.

أسلوب الرد:
- احترافي، واضح، منظم
- لهجة سعودية رسمية
- بدون حشو

بداية الرد:
- "حياك الله،"
- "أهلًا وسهلًا،"

ثم:
"بناءً على الأنظمة ذات العلاقة..."

القواعد:
- الاعتماد فقط على المعلومات المتوفرة
- لا يتم اختراع معلومات
- ذكر المواد عند توفرها
- تقديم إجابة متكاملة بدون تكرار

في حال عدم كفاية المعرفة:
"الموضوع هذا يحتاج تحقق أدق، وننصح بالرجوع لجهة مختصة أو مستشار قانوني لضمان الإجابة الصحيحة."

الهوية:
- يعكس فريق استشاري موثوق (بصيرة)
"""

def get_persona(namespace: str) -> tuple[str, str]:
    """يرجع (system_prompt, اسم_الشخصية)"""
    if namespace == NS_RENT:
        return SARAH_SYSTEM, "سارة"
    elif namespace == NS_LABOR:
        return MUHAMMAD_SYSTEM, "محمد"
    elif namespace == NS_NDA:
        return JOUD_SYSTEM, "جود"
    else:
        return BOTH_SYSTEM, "الفريق القانوني"

import openai
import tiktoken
from tenacity import retry, wait_exponential, stop_after_attempt

ENC = tiktoken.get_encoding('cl100k_base')

SCORE_THRESHOLD = 0.45
TOP_K_RETRIEVE  = 15
TOP_K_FINAL     = 5

NS_RENT  = "rent"
NS_LABOR = "labor"
NS_NDA   = "nda"


def detect_namespace(query: str) -> str:
    rent_keywords  = ['إيجار','مستأجر','مؤجر','إخلاء','عقار','شقة','تجديد عقد','rent','tenant','landlord','وحدة سكنية']
    labor_keywords = [
        'عمل','عامل','صاحب عمل','راتب','إنهاية خدمة',
        'مكافأة','تعويض','نهاية الخدمة',
        'أجر','سنوات خدمة','فصل','استقالة',
        'labor','employee','salary','termination'
    ]
    nda_keywords = [
        'سرية','إفصاح','عدم إفصاح','كتمان','بيانات','معلومات سرية',
        'المنافسة','عدم منافسة','اتفاقية سرية','nda','confidentiality','disclosure','non-compete'
    ]

    q = query.lower()
    rent_match  = any(kw in q for kw in rent_keywords)
    labor_match = any(kw in q for kw in labor_keywords)
    nda_match   = any(kw in q for kw in nda_keywords)

    if nda_match and not (rent_match or labor_match):
        return NS_NDA
    elif rent_match and not (labor_match or nda_match):
        return NS_RENT
    elif labor_match and not (rent_match or nda_match):
        return NS_LABOR
    else:
        return 'both'

@retry(
    retry=retry_if_exception_type((openai.RateLimitError, openai.APIError)),
    wait=wait_exponential(multiplier=1, min=2, max=60),
    stop=stop_after_attempt(5)
)
def embed_batch(texts: list) -> list:
    response = client.embeddings.create(model='text-embedding-3-large', input=texts)
    return [item.embedding for item in response.data]

def generate_multi_queries(original_query: str) -> list:
    response = client.chat.completions.create(
        model='gpt-4o-mini',
        messages=[
            {'role': 'system', 'content': (
                'أنت مساعد قانوني. صغ 3 طرق مختلفة للسؤال التالي '
                'لتغطية مصطلحات مختلفة في قاعدة البيانات. '
                'اكتب كل صياغة في سطر منفصل فقط بدون ترقيم.'
            )},
            {'role': 'user', 'content': original_query}
        ],
        temperature=0.3,
        max_tokens=200
    )
    lines   = response.choices[0].message.content.strip().split('\n')
    queries = [original_query] + [l.strip() for l in lines if l.strip()]

    hyde_response = client.chat.completions.create(
        model='gpt-4o-mini',
        messages=[{
            'role': 'user',
            'content': (
                f'اكتب فقرة قصيرة تبدو كنص من نظام العمل السعودي '
                f'أو نظام الإيجار تجيب على: {original_query}'
            )
        }],
        temperature=0.1,
        max_tokens=150
    )
    hyde_text = hyde_response.choices[0].message.content.strip()
    queries.append(hyde_text)

    return queries[:5]

def retrieve_chunks_raw(query: str, namespace: str, top_k: int = TOP_K_RETRIEVE) -> list:
    q_vector   = embed_batch([query])[0]
    if namespace == 'both':
        namespaces = [NS_RENT, NS_LABOR, NS_NDA]
    else:
        namespaces = [namespace]

    all_chunks = []
    for ns in namespaces:
        result = index.query(
            vector=q_vector, top_k=top_k,
            namespace=ns, include_metadata=True
        )
        for match in result.matches:
            if match.score >= SCORE_THRESHOLD:
                all_chunks.append({
                    'id'         : match.id,
                    'score'      : round(match.score, 3),
                    'text'       : match.metadata.get('text', ''),
                    'namespace'  : ns,
                    'reference'  : match.metadata.get('reference', ''),
                    'source_file': match.metadata.get('source_file', ''),
                })
    return all_chunks

def rerank_chunks(query: str, chunks: list, top_k: int = TOP_K_FINAL) -> list:
    if not chunks:
        return []
    pairs  = [(query, c['text']) for c in chunks]
    scores = reranker.predict(pairs)
    for chunk, score in zip(chunks, scores):
        chunk['rerank_score'] = float(score)
    reranked = sorted(chunks, key=lambda x: x['rerank_score'], reverse=True)
    return reranked[:top_k]

def build_context(chunks: list) -> str:
    if not chunks:
        return 'لا توجد نتائج ذات صلة.'
    parts = []
    for i, c in enumerate(chunks, 1):
        ref  = f" [{c['reference']}]" if c.get('reference') else ''
        src  = f" (ملف: {c['source_file']})" if c.get('source_file') else ''
        parts.append(f"[{i}] ns={c['namespace']}{ref}{src}\n{c['text']}")
    return '\n\n'.join(parts)

def legal_rag(question: str, verbose: bool = False) -> str:
    namespace = detect_namespace(question)
    system_prompt, who = get_persona(namespace)

    if verbose:
        print(f"--- Persona: {who} | Namespace: {namespace} ---")

    all_queries = generate_multi_queries(question)

    unique_chunks: dict = {}
    for q in all_queries:
        chunks = retrieve_chunks_raw(q, namespace)
        for chunk in chunks:
            cid = chunk['id']
            if cid not in unique_chunks:
                unique_chunks[cid] = chunk
            else:
                unique_chunks[cid]['score'] = max(unique_chunks[cid]['score'], chunk['score'])

    raw_chunks = sorted(unique_chunks.values(), key=lambda x: x['score'], reverse=True)

    reranked = rerank_chunks(question, raw_chunks, top_k=TOP_K_FINAL)

    if not reranked:

        full_context = "لا توجد معلومات ذات صلة في قاعدة البيانات."
    else:
        full_context = build_context(reranked)


    response = client.chat.completions.create(
        model='gpt-4o',
        messages=[
            {'role': 'system', 'content': system_prompt},
            {'role': 'user', 'content': f'السياق المستخرج:\n{full_context}\n\nالسؤال: {question}'}
        ],
        temperature=0,
        max_tokens=1500
    )

    answer = response.choices[0].message.content
    return f"[{who}]: {answer}"

q1 = "كيف يجب على صاحب العمل إعلان لائحة تنظيم العمل للعمال؟ "

print(legal_rag(q1, verbose=True))

q1 = "متى يجب على المنشأة تحديث بياناتها في المنصة المعتمدة في حال تغيير عنوانها؟ "
print(legal_rag(q1, verbose=True))

q1 = "هل المؤجر مسؤول عن العيوب الخفية في العقار؟"
print(legal_rag(q1, verbose=True))

q1 = " هل يحق لصاحب العمل تحديد موعد الإجازة؟"
print(legal_rag(q1, verbose=True))

q1 = "كم الاجازة السنوية المستحقة لي"
print(legal_rag(q1, verbose=True))

q1 = " هل يحق للطرف المستلم استخدام المعلومات السرية في مشروع آخر طالما التزم بعدم كشفها للآخرين؟"
print(legal_rag(q1, verbose=True))